### ISSUE TITLE
Creating a menu

### ISSUE THREAD

**Issue by chideraeze** [chideraeze/python-exercise#1]
The task for the project is to create a menu that has an option for quit so that when a user types q the program exits. 

**Task List**
- [ ] Have an option for q to quit. 
- [ ] if the user uses q, the program exits.
- [ ] if the user types an invalid option, the menu reappears for the user to type again.

**Acceptance Criteria** 
- [ ] The menu should have an option for quitting the program.
- [ ] If the user types an invalid option, the menu should reappear.

**Acceptance Test 1**: 
- Input: User types 'q'
- Expected Output: Program exits

**Acceptance Test 2**:
- Input: User types an invalid option, then '1'
- Expected Output: User is prompted to try again, and the list of movies is displayed.

**Comment by chideraeze** [comment]
changes have been implemented and merged.
