### ISSUE TITLE
Search Movies by Cast

### ISSUE THREAD

**Issue by chideraeze** [chideraeze/python-exercise#7]
** Description**
Adding an option to the menu that allows users to search for movies by their cast members. The search should list all movies that have the provided word in their cast (case-insensitive) and also provide the full names of actor/actress that contain the word. 

**Task List**
- [ ] Add a new option in the menu for searching movies by cast.
- [ ] Implement the functionality to enter a search word.
- [ ] Perform a case-insensitive search for movies and cast members.
- [ ] Display matching movies and the full names of actors/actresses.

**Acceptance Criteria**
- [ ] There should be a new menu option for searching movies by cast.
- [ ] Selecting this option should allow the user to enter a search word.
- [ ] The search should be case-insensitive.
- [ ] The program should list all movies with cast members containing the search word.
- [ ] The program should provide the full names of actors/actresses containing the search word.

**Acceptance Test 1:**
- Input: User selects the option to search movies by cast and enters "johnson" as the search word.
- Expected Output: The program displays a list of movies with cast members containing "johnson" and provides the full names of those actors/actresses.

**Acceptance Test 2:**
- Input: User selects the option to search movies by cast and enters "smith" as the search word.
- Expected Output: The program displays a list of movies with cast members containing "smith" and provides the full names of those actors/actresses.

**Acceptance Test 3:**
- Input: User selects the option to search movies by cast and enters "xyz" as the search word (no matching cast members).
- Expected Output: The program displays a message indicating that no matching movies or cast members were found.

**Comment by chideraeze** [comment]
The changes have been implemented and merged.
